#!/bin/bash

# Usage: ./open
#        ./open <year> <day>

if [ -z "$1" ] || [ -z "$2" ]; then
  year=$(ls -1 | grep -E '^[0-9]{4}$' | sort | tail -1)
  day=$(($(ls -1 "$year" | sort | tail -1 | sed 's/day0//' | sed 's/day//')))
else
  year=$1
  day=$2
fi

open "https://adventofcode.com/$year/day/$day"
